#!/usr/bin/env node

var http = require('http') 
var program = require('commander');

program
  .version('0.0.0')
  .option('-u, --url <url>', 'URL of the Phant server. Ex. http://data.sparkfun.com')
  .option('-s, --public_key <public_key>', 'The public key Phant gave you for this stream')
  .option('-p, --private_key <private_key>', 'The private key Phant gave you for this stream')
  .option('-f, --field_name <field_name>', 'Field name you told Phant you would use for this stream')
  .option('-d, --data <data>', 'Data! Yum yum.')
  .parse(process.argv);

if (program.data) {
  go()
}
else {
  program.data = ''
  process.stdin.on('data', function(chunk) {
    if (chunk)
      program.data += chunk
  })
  process.stdin.on('end', function() {
    go()
  })
}

function go() {
  var path = '/input/' + program.public_key + 
    '?private_key=' + program.private_key + 
    '&' + program.field_name + '=' + program.data;
  http.get({ host: program.url, path: path}, function(response) {
    response.on('error', function() {
      console.log('error!')
      process.exit(1)
    })
    response.on('data', function() {
      console.log(response.statusCode) // 200 
      process.exit(0)
    })
  })
}
