#!/usr/bin/env node

var fs = require('fs')
var request = require('request')

var args = process.argv.slice(2);
var send = args[0]

var config = JSON.parse(fs.readFileSync(__dirname + '/../../config.json', 'utf8'))
var iri = config.phant.iri 

request
  .get(iri + send)
  .on('response', function(response) {
    console.log(response.statusCode) // 200 
  })

console.log("sending: " + send)
